# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: riethmayer.de
url:   http://riethmayer.de
author: 
  name:    Jan Riethmayer        # For copyright notice and ATOM feeds
  email:   jan@riethmayer.de # Exception emails will go here, and it is used in ATOM feeds
  open_id:                  # These are used to login to the admin area
      - http://riethmayer.myopenid.com
      - https://me.yahoo.com/jan.riethmayer